// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRfxj1cIvtwxz7HdQF-pJafw-TZyirvSI',
    appId: '1:386742106425:web:bb55d618cd9aabf8d990e8',
    messagingSenderId: '386742106425',
    projectId: 'rowing-navigator',
    authDomain: 'rowing-navigator.firebaseapp.com',
    storageBucket: 'rowing-navigator.appspot.com',
    measurementId: 'G-QCQ6BWT8F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf05QMXE2pppaED34xiTneoBPbxoVSUVo',
    appId: '1:386742106425:android:754f9a8dffbc7015d990e8',
    messagingSenderId: '386742106425',
    projectId: 'rowing-navigator',
    storageBucket: 'rowing-navigator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoAS8VvN9v1HQHj3eHFsLrGiN9QpsZiCk',
    appId: '1:386742106425:ios:c665e66c2b64068bd990e8',
    messagingSenderId: '386742106425',
    projectId: 'rowing-navigator',
    storageBucket: 'rowing-navigator.appspot.com',
    iosBundleId: 'com.obashun.rowing-navigator',
  );
}
