// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA55n308sX8O86-GXrA9P9XxqIssq-zJoI',
    appId: '1:430420830197:web:87e1dde5e7585e846de2bc',
    messagingSenderId: '430420830197',
    projectId: 'rowing-navigator-tsukuba',
    authDomain: 'rowing-navigator-tsukuba.firebaseapp.com',
    databaseURL:
        'https://rowing-navigator-tsukuba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rowing-navigator-tsukuba.firebasestorage.app',
    measurementId: 'G-31KFELJVP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCHgU1k1P_OmE_ee7Rn8UAscRS78eCPq4',
    appId: '1:430420830197:android:ebd7abdd340fc5e96de2bc',
    messagingSenderId: '430420830197',
    projectId: 'rowing-navigator-tsukuba',
    databaseURL:
        'https://rowing-navigator-tsukuba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rowing-navigator-tsukuba.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0UkF2OFt_9U4UyO81t4MIZmQYhskjth4',
    appId: '1:430420830197:ios:a6befdb39770f60c6de2bc',
    messagingSenderId: '430420830197',
    projectId: 'rowing-navigator-tsukuba',
    databaseURL:
        'https://rowing-navigator-tsukuba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rowing-navigator-tsukuba.firebasestorage.app',
    iosBundleId: 'jp.kosei.rowingnavigator.tsukuba',
  );
}
