import 'dart:convert';
import 'dart:io';

/// 同梱プロファイルから校正対象のDart定数とFirestore Rules生成ブロックを作る。
/// ashoreAreas/navigableWatersは校正対象外なので意図的に含めない。
Future<void> main(List<String> arguments) async {
  final checkOnly = arguments.contains('--check');
  final profileFile = File('assets/data/sakuragawa_obstacles.json');
  final profile =
      jsonDecode(await profileFile.readAsString()) as Map<String, dynamic>;
  final items = <Map<String, dynamic>>[
    ...((profile['obstacles'] as List)
        .cast<Map>()
        .map((item) => Map<String, dynamic>.from(item))),
    ...((profile['dangerZoneBaselines'] as List)
        .cast<Map>()
        .map((item) => Map<String, dynamic>.from(item))),
  ];
  final ids = <String>[];
  final counts = <String, int>{};
  for (final item in items) {
    final id = item['id'];
    final points = item['points'];
    if (id is! String || points is! List || counts.containsKey(id)) {
      throw FormatException(
          'Invalid or duplicate calibratable profile item: $id');
    }
    ids.add(id);
    counts[id] = points.length;
  }
  final dart = _dartSource(ids, counts);
  final rules = _rulesBlock(ids, counts);
  await _writeOrCheck(
      File('lib/models/shared_safety_calibration.g.dart'), dart, checkOnly);
  final rulesFile = File('firestore.rules');
  final currentRules = await rulesFile.readAsString();
  const begin = '// GENERATED: hazard-allowlist BEGIN';
  const end = '// GENERATED: hazard-allowlist END';
  final start = currentRules.indexOf(begin);
  final finish = currentRules.indexOf(end);
  if (start < 0 || finish < start) {
    throw StateError('Missing Firestore Rules generated block markers');
  }
  final updatedRules =
      '${currentRules.substring(0, start)}$rules${currentRules.substring(finish + end.length)}';
  await _writeOrCheck(rulesFile, updatedRules, checkOnly);
}

Future<void> _writeOrCheck(File file, String contents, bool checkOnly) async {
  final current = await file.readAsString();
  if (current == contents) return;
  if (checkOnly) {
    stderr.writeln('Generated hazard constants are stale: ${file.path}');
    exitCode = 1;
    return;
  }
  await file.writeAsString(contents);
  stdout.writeln('Generated ${file.path}');
}

String _dartSource(List<String> ids, Map<String, int> counts) =>
    '''// GENERATED by tool/generate_hazard_constants.dart. Do not edit.

const generatedAllowedSourceIds = <String>{
${ids.map((id) => "  '$id',").join('\n')}
};

const generatedVertexPointCounts = <String, int>{
${ids.map((id) => "  '$id': ${counts[id]},").join('\n')}
};
''';

String _rulesBlock(List<String> ids, Map<String, int> counts) =>
    '''// GENERATED: hazard-allowlist BEGIN
    function validHazardSourceIds(values) {
      return values.keys().hasOnly([
${ids.map((id) => "        '$id',").join('\n')}
      ]);
    }

    function validScaledOffsetMap(values) {
      // 全sourceを個別型検査するとFirestore Rulesの1000式上限を超える。
      // 未知IDはここで拒否し、GeoPoint型・値域は読込時にも検証して、
      // 不正な共有文書は適用せず最後の正常cacheを維持する。
      return values is map
        && validHazardSourceIds(values);
    }

    function validScaledVertexOffsets(values) {
      return values is map
        && validHazardSourceIds(values)
${ids.map((id) => "        && (!('$id' in values) || validScaledVertexOffsetList(values.$id, ${counts[id]}))").join('\n')};
    }

    function validDisabledWarningSourceIds(values) {
      return values is list
        && values.size() <= ${ids.length}
        && values.hasOnly([
${ids.map((id) => "          '$id',").join('\n')}
        ]);
    }
// GENERATED: hazard-allowlist END''';
