import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { relative, resolve } from 'node:path';
import { exportLayout } from '../src/io/layout';
import { exportProfileText, profileObject } from '../src/io/profile';
import type { MapObject, Project } from '../src/model/types';
import { DANGER_BASELINE_KINDS, DANGER_POLYGON_KINDS } from '../src/model/types';
import { validateProject } from '../src/validate/project';

function timestampPathPart() { return new Date().toISOString().replace(/[:.]/g, '-'); }
function sha256(value: string) { return createHash('sha256').update(value).digest('hex'); }
const handoffRootName = '障害物座標プロット_変更適用';
function points(object: MapObject) { return object.geometry.type === 'point' ? [object.geometry.point] : object.geometry.points; }
function calibrationObjects(project: Project) {
  return project.objects.filter((object) => DANGER_BASELINE_KINDS.has(object.kind) || DANGER_POLYGON_KINDS.has(object.kind));
}
function dartFragment(objects: MapObject[]) {
  const ids = objects.map((object) => object.exportId).sort();
  const counts = objects.map((object) => `    '${object.exportId}': ${points(object).length},`).sort();
  return `// GENERATED by tool/generate_hazard_constants.dart. Do not edit.\nconst allowedSourceIds = <String>{\n${ids.map((id) => `  '${id}',`).join('\n')}\n};\n\nconst vertexPointCounts = <String, int>{\n${counts.join('\n')}\n};\n`;
}
function rulesFragment(objects: MapObject[]) {
  const ids = objects.map((object) => object.exportId).sort();
  const checks = objects.map((object) => `        && (!values.keys().hasAny(['${object.exportId}']) || validScaledVertexOffsetList(values.${object.exportId}, ${points(object).length}))`).join('\n');
  return `// GENERATED: hazard-allowlist BEGIN\nfunction validScaledVertexOffsets(values) {\n  return values is map\n    && values.keys().hasOnly([${ids.map((id) => `'${id}'`).join(', ')}])\n${checks};\n}\n// GENERATED: hazard-allowlist END\n`;
}
function changesetMarkdown(project: Project, profileHash: string, count: number, issues: ReturnType<typeof validateProject>) {
  const errors = issues.filter((issue) => issue.level === 'error');
  const warnings = issues.filter((issue) => issue.level === 'warning');
  const validationStatus = errors.length
    ? `\n> **未完成データ**: 検証エラー ${errors.length} 件、警告 ${warnings.length} 件を含みます。座標データと詳細は \`changeset.json\` に出力済みです。そのままアプリへ適用せず、AIエージェントで修正後に再検証してください。\n`
    : warnings.length
      ? `\n> 検証警告 ${warnings.length} 件があります。詳細は \`changeset.json\` を確認してください。\n`
      : '\n> 検証エラー・警告はありません。\n';
  const hasAshore = project.objects.some((object) => object.kind === 'ashoreArea');
  const centerlines = project.objects.filter((object) => object.kind === 'channelCenterline');
  const lanes = project.objects.filter((object) => object.kind === 'lane');
  const laneSummary = lanes.length === 0
    ? 'なし（アプリは cross 符号方式へ縮退）'
    : `${lanes.length}枚(${lanes.map((lane) => `${lane.centerlineId ?? '中心線未指定'}:${lane.laneDirection ?? 'direction未指定'}`).join(' / ')})`;
  const promotedIds = project.objects.flatMap((object) => object.promotedFromTemporaryDocId ? [object.promotedFromTemporaryDocId] : []);
  let sourceCleanup = promotedIds.length
    ? `\n## 昇格元の臨時障害物（削除は配布後）\n\n次のFirestore文書は、**このプロファイルを含む配布版を実機で確認した後**に、アプリの地図編集画面から手動削除する。配布前には削除しない。\n\n${promotedIds.map((id) => `- \`${id}\``).join('\n')}\n`
    : '';
  sourceCleanup += `\n## 検証状態\n${validationStatus}`;
  return `# 危険区域データ変更適用手順\n\n## 生成結果\n\n- profile version: ${project.profileVersion}\n- SHA-256: \`${profileHash}\`\n- 校正対象の固定危険区域: ${count} 件\n- 陸上エリア: ${hasAshore ? 'あり' : 'なし（アプリは音を止めない）'}\n- 航路レーン: ${laneSummary}\n- 航路中心線: ${centerlines.length ? `${centerlines.length}本(${centerlines.map((line) => line.exportId).join(' / ')})` : '岸から自動導出（要手動プロット）'}\n- 校正差分の焼き込み: ${project.bakedCalibration ? 'あり。profileVersionの更新を確認済み。' : 'なし'}\n\n## 必須の反映\n\n1. \`files/sakuragawa_obstacles.json\` を \`assets/data/sakuragawa_obstacles.json\` へ反映する。\n2. \`files/sakuragawa_obstacles.layout.json\` を \`assets/data/\` へ反映する。\n3. \`dart run tool/generate_hazard_constants.dart\` を実行し、生成物とFirestore Rulesを更新する。\n4. \`tool/update_hazard_profile_hash.sh\` を実行し、SHA-256が \`${profileHash}\` になることを確認する。\n5. \`verify.sh\` を実行する。${sourceCleanup}\n## 注意\n\n- 変更適用パッケージはFireStoreへ書き込みません。\n- 実機・水上での検証は別の必須ゲートです。水上で音が止まらないことを必ず確認してください。\n`;
}

export async function writeChangeset(repoRoot: string, project: Project) {
  const issues = validateProject(project);
  const errors = issues.filter((issue) => issue.level === 'error');
  // Keep handoff packages beside the repository so Codex can review an immutable
  // proposal without the tool writing into application assets.
  const target = resolve(repoRoot, '..', handoffRootName, `${timestampPathPart()}${errors.length ? '-INCOMPLETE' : ''}`);
  const files = resolve(target, 'files');
  const constants = resolve(target, 'constants');
  await mkdir(files, { recursive: true });
  await mkdir(constants, { recursive: true });
  const profile = exportProfileText(project);
  const profileHash = sha256(profile);
  const calibratable = calibrationObjects(project);
  await Promise.all([
    writeFile(resolve(files, 'sakuragawa_obstacles.json'), profile),
    writeFile(resolve(files, 'sakuragawa_obstacles.layout.json'), exportLayout(project)),
    writeFile(resolve(constants, 'shared_safety_calibration.dart.fragment'), dartFragment(calibratable)),
    writeFile(resolve(constants, 'firestore.rules.fragment'), rulesFragment(calibratable)),
    writeFile(resolve(constants, 'hazard_profile_config.expected.md'), `currentHazardProfileDataVersion: ${project.profileVersion}\ncurrentHazardProfileSha256: ${profileHash}\n`),
    writeFile(resolve(target, 'CHANGESET.md'), changesetMarkdown(project, profileHash, calibratable.length, issues)),
    writeFile(resolve(target, 'changeset.json'), `${JSON.stringify({ generatedAt: new Date().toISOString(), profileSha256: profileHash, profileVersion: project.profileVersion, validation: issues, profile: profileObject(project) }, null, 2)}\n`),
    writeFile(resolve(target, 'verify.sh'), '#!/usr/bin/env bash\nset -euo pipefail\ncd "$(git rev-parse --show-toplevel)"\ntool/update_hazard_profile_hash.sh --check\ndart run tool/generate_hazard_constants.dart --check\ndart analyze lib test\nflutter test\ncd firebase_rules_test && npm test\n'),
  ]);
  return relative(repoRoot, target);
}
